### ISSUE TITLE
Screen resolution issue when porting to 320x240

### ISSUE THREAD

**Issue by andymcca** [gameblabla/dumbsnes#1]
Hi!

Firstly, thanks so much for this project - it actually works on the Leapster Explorer 32MB/Didj devices (standard PocketSNES doesn't work at 32MB).

I notice in the code that the SDL surface is set to 320x480 for the RS-97.  Weirdly, this works fine on the Explorer which has a 320x240 screen.  But if I try and change the SDL surface size in the code, and other relevant sections, to 320x240, and then build it, I only get half a display (i.e. 320x480 on a 320x240 screen)!  I'm guessing I'm missing something in the code e.g. a screen buffer or something that caters for the bigger display.  Any ideas?

**Comment by gameblabla** [comment]
That's 100% intended as it was meant for the RS-97 as you said. Nowadays, that code can be taken out but there are better suitable emulators for the Leapster Explorer. Something like my fork https://github.com/gameblabla/snesemu should be better (although maybe not as smooth although it does have this performance fix : https://github.com/gameblabla/snesemu/commit/435a5ef19ed64121a87df4d4e7b420ae8b5a1ea4)
